version: "3.8"
services:
  app:
    build:
      context: ./
    tty: true
    container_name: go-template
    env_file:
      - .env.local
    volumes:
      - ../:/work/app
      - ~/.gitconfig:/root/.gitconfig
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    working_dir: /work/app
    ports:
      - "8000:8000"
