version: "3.8"
services:
  app:
    build:
      context: ./
    tty: true
    container_name: go-template
    volumes:
      - ../:/app
      - ~/.gitconfig:/root/.gitconfig
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    working_dir: /app
    ports:
      - "8000:8000"
